[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.setuptools_scm]
write_to = "mkctf/__version__.py"
