# ==============================================================================
# Standard categories
# ==============================================================================
tags:
    - for
    - rev
    - pwn
    - web
    - web3
    - prog
    - osint
    - radio
    - crypto
    - mobile
    - bounty
    - stegano
# ==============================================================================
# Standard difficulties
# ==============================================================================
difficulties:
    - very easy
    - easy
    - medium
    - hard
    - insane
# ==============================================================================
# Standard flag information
# ==============================================================================
flag:
    prefix: 'ECTF{'
    suffix: '}'
# ==============================================================================
# Standard DNS information
# ==============================================================================
domain: example.ctf
# ==============================================================================
# Standard Docker information
# ==============================================================================
docker:
    user: examplectf
    registry: registry.example.ctf
