from .build import setup_build
from .configure import setup_configure
from .create import setup_create
from .delete import setup_delete
from .deploy import setup_deploy
from .disable import setup_disable
from .enable import setup_enable
from .enum import setup_enum
from .export import setup_export
from .init import setup_init
from .push import setup_push
from .renew_flag import setup_renew_flag
from .healthcheck import setup_healthcheck
from .update_meta import setup_update_meta
